version: "3.9"

services:
  web:
    build: .
    container_name: imersao-app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
